<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Card_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Card_type_model');
    } 

    /*
     * Listing of card_types
     */
    function index()
    {
        $data['card_types'] = $this->Card_type_model->get_all_card_types();
        
        $data['_view'] = 'card_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new card_type
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('CardType','CardType','required|is_unique[card_type.CardType]|max_length[40]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'CardType' => $this->input->post('CardType'),
            );
            
            $card_type_id = $this->Card_type_model->add_card_type($params);
            redirect('card_type/index');
        }
        else
        {            
            $data['_view'] = 'card_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a card_type
     */
    function edit($CardTypeID)
    {   
        // check if the card_type exists before trying to edit it
        $data['card_type'] = $this->Card_type_model->get_card_type($CardTypeID);
        
        if(isset($data['card_type']['CardTypeID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('CardType','CardType','required|is_unique[card_type.CardType]|max_length[40]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'CardType' => $this->input->post('CardType'),
                );

                $this->Card_type_model->update_card_type($CardTypeID,$params);            
                redirect('card_type/index');
            }
            else
            {
                $data['_view'] = 'card_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The card_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting card_type
     */
    function remove($CardTypeID)
    {
        $card_type = $this->Card_type_model->get_card_type($CardTypeID);

        // check if the card_type exists before trying to delete it
        if(isset($card_type['CardTypeID']))
        {
            $this->Card_type_model->delete_card_type($CardTypeID);
            redirect('card_type/index');
        }
        else
            show_error('The card_type you are trying to delete does not exist.');
    }
    
}
