<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bank by BankID
     */
    function get_bank($BankID)
    {
        return $this->db->get_where('banks',array('BankID'=>$BankID))->row_array();
    }
        
    /*
     * Get all banks
     */
    function get_all_banks()
    {
        $this->db->order_by('BankID', 'desc');
        return $this->db->get('banks')->result_array();
    }
        
    /*
     * function to add new bank
     */
    function add_bank($params)
    {
        $this->db->insert('banks',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bank
     */
    function update_bank($BankID,$params)
    {
        $this->db->where('BankID',$BankID);
        return $this->db->update('banks',$params);
    }
    
    /*
     * function to delete bank
     */
    function delete_bank($BankID)
    {
        return $this->db->delete('banks',array('BankID'=>$BankID));
    }
}
