<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Card_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get card_type by CardTypeID
     */
    function get_card_type($CardTypeID)
    {
        return $this->db->get_where('card_types',array('CardTypeID'=>$CardTypeID))->row_array();
    }
        
    /*
     * Get all card_types
     */
    function get_all_card_types()
    {
        $this->db->order_by('CardTypeID', 'desc');
        return $this->db->get('card_types')->result_array();
    }
        
    /*
     * function to add new card_type
     */
    function add_card_type($params)
    {
        $this->db->insert('card_types',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update card_type
     */
    function update_card_type($CardTypeID,$params)
    {
        $this->db->where('CardTypeID',$CardTypeID);
        return $this->db->update('card_types',$params);
    }
    
    /*
     * function to delete card_type
     */
    function delete_card_type($CardTypeID)
    {
        return $this->db->delete('card_types',array('CardTypeID'=>$CardTypeID));
    }
}
