<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Good_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get good by GoodID
     */
    function get_good($GoodID)
    {
        return $this->db->get_where('goods',array('GoodID'=>$GoodID))->row_array();
    }
    
    /*
     * Get all goods count
     */
    function get_all_goods_count()
    {
        $this->db->from('goods');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all goods
     */
    function get_all_goods($params = array())
    {
        $this->db->order_by('GoodID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('goods')->result_array();
    }
        
    /*
     * function to add new good
     */
    function add_good($params)
    {
        $this->db->insert('goods',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update good
     */
    function update_good($GoodID,$params)
    {
        $this->db->where('GoodID',$GoodID);
        return $this->db->update('goods',$params);
    }
    
    /*
     * function to delete good
     */
    function delete_good($GoodID)
    {
        return $this->db->delete('goods',array('GoodID'=>$GoodID));
    }
}
