<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Purchase_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get purchase by PurchaseID
     */
    function get_purchase($PurchaseID)
    {
        return $this->db->get_where('purchases',array('PurchaseID'=>$PurchaseID))->row_array();
    }
    
    /*
     * Get all purchases count
     */
    function get_all_purchases_count()
    {
        $this->db->from('purchases');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all purchases
     */
    function get_all_purchases($params = array())
    {
        $this->db->order_by('PurchaseID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('purchases')->result_array();
    }
        
    /*
     * function to add new purchase
     */
    function add_purchase($params)
    {
        $this->db->insert('purchases',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update purchase
     */
    function update_purchase($PurchaseID,$params)
    {
        $this->db->where('PurchaseID',$PurchaseID);
        return $this->db->update('purchases',$params);
    }
    
    /*
     * function to delete purchase
     */
    function delete_purchase($PurchaseID)
    {
        return $this->db->delete('purchases',array('PurchaseID'=>$PurchaseID));
    }
}
