<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Store_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get store by StoreID
     */
    function get_store($StoreID)
    {
        return $this->db->get_where('stores',array('StoreID'=>$StoreID))->row_array();
    }
        
    /*
     * Get all stores
     */
    function get_all_stores()
    {
        $this->db->order_by('StoreID', 'desc');
        return $this->db->get('stores')->result_array();
    }
        
    /*
     * function to add new store
     */
    function add_store($params)
    {
        $this->db->insert('stores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update store
     */
    function update_store($StoreID,$params)
    {
        $this->db->where('StoreID',$StoreID);
        return $this->db->update('stores',$params);
    }
    
    /*
     * function to delete store
     */
    function delete_store($StoreID)
    {
        return $this->db->delete('stores',array('StoreID'=>$StoreID));
    }
}
