<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by UserID
     */
    function get_user($UserID)
    {
        return $this->db->get_where('users',array('UserID'=>$UserID))->row_array();
    }
        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $this->db->order_by('UserID', 'desc');
        return $this->db->get('users')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($UserID,$params)
    {
        $this->db->where('UserID',$UserID);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($UserID)
    {
        return $this->db->delete('users',array('UserID'=>$UserID));
    }
    
    /*
     * function to log user in
     */
    public function login($password) {
        // Validate
        $this->db->where('UserName', 'BookkeepingAdmin');
        $this->db->where('Password', $password);
        
        $result = $this->db->get('users');
        
        if($result->num_rows() == 1) {
            return TRUE;
        } else {
            return FALSE;
        }
    }
}
